### ISSUE TITLE
Deployed directory structure and dependencies

### ISSUE THREAD

**Issue by HyveMynd** [serverless/serverless-azure-functions#34] opened 2017-03-01 01:52 UTC
What is the proper behavior in regards to dependencies? Currently, only the entry file is uploaded to Azure and a `function.json` is automatically created and uploaded to the function directory.  

i.e.

|-handler.js
|-serverless.yml

becomes,

|-functionName/
|--index.js
|--function.json

However if I create a new directory and file which is required by the entry file (handler.js in the example) the dependencies do not get uploaded.

i.e.

|-lib/
|--other.js     <- library file
|-handler.js   <- requires library file
|-serverless.yml

still produces,

|-functionName/
|--index.js
|--function.json

Running the function will throw a module not found error when required. Meaning the dependencies were not bundled with the file.

This differs from the behavior of other providers. Particularly AWS where all the dependencies are automatically bundled and uploaded.

Is this behavior expected or am I missing something? Will there be changes made to function similarly to the other providers?

Thanks!

Example Repo:
1. `git clone https://github.com/HyveMynd/azure-test.git`
2. `npm i`
3. `sls deploy`

**Comment by pragnagopa** [comment] 2017-03-01 17:49
Thanks for the feedback!  As of now deploy is not uploading any other files other than handler code. Will discuss with @christopheranderson and provide a way to include dependent files.

**Comment by christopheranderson** [comment] 2017-03-05 04:36
I've been thinking about this. I'm thinking of actually moving to a central directory where we upload the source, then generating function.json with pointers to the right files.

So my project might look like 
```
|-serverless.yml
|-package.json
|-handler.js
|-lib
|--index.js
```

We then take the whole contents of the service project's directory and put it into the project under say ".source".

Then function.json for a given function could point at:
"scriptFile":".source/hander.js"

We can meet up on Monday and sketch out some ideas. With the move to the archive library over the ZIP library, uploads should be pretty simple. 

I wonder what the value of updating a single function becomes if its all sharing the same code. That makes more sense when you have each function as a separate resource.

**Comment by truztee** [comment] 2017-04-13 11:03
A somewhat related problem, I was using the deploy command with serverless-babel-plugin defined, the plugin created the zip file correctly under .serverless/[function-name].zip containing all the dependency files  with the excluded folder/files specified in serverless.yaml correctly excluded from the zip file.

But the problem is that the Azure plugin does not use the plugin hook lifecycle that the serverless-babel-plugin used, so the zip file from babel plugin got ignored and Azure plugin uploads it's own zip file containing only the index.js file without the other dependency files.

So perhaps by utilizing the babel-plugin we can create the correct package file with all the dependency without the need of a special folder structure.

**Comment by kennu** [comment] 2017-04-18 15:40
Wouldn't it be easiest to use the .zip file that Serverless already creates in .serverless according to include/exclude rules and just add a function.json to it?

**Comment by christopheranderson** [comment] 2017-04-19 15:41
I think your strategy is the right one, @kennu. I've been thinking this is the right approach myself.

**Comment by johngully** [comment] 2017-05-13 05:59
I'm having the same issue.  The ability to modularize the code into testable units independent of the "function" is essential to being able to write something more complex.  Until this is corrected I can't see how to use Azure functions in a meaningful way.  

Am I missing something?

**Comment by HyveMynd** [comment] 2017-06-05 21:56
any progress on this issue?

**Comment by pragnagopa** [comment] 2017-06-06 17:40
@fiveisprime  - Matt, can you please follow up on this?

**Comment by drandx** [comment] 2017-06-28 15:38
Do we have any update on this? :)

**Comment by arunshan** [comment] 2017-07-14 11:13
Somewhat related to this issue but I can create a new one if this does not belong here. 

Would be great to have individual testable units/files and package them using https://serverless.com/framework/docs/providers/azure/guide/packaging/

For some reason packaging specific files using `include` does not add those specific files in the final deploy.  I dont know if I am missing something but this is how my serverless.yml file looks like

```
process:
    handler: operations/translate.process
    package:
      include:
        - config.json
```

**Closed** 2017-08-20 21:30 UTC
Labels: improvement
