### ISSUE TITLE
Throw errors if the Rest API calls return non success HTTP status code

### ISSUE THREAD

**Issue by pragnagopa** [serverless/serverless-azure-functions#28] opened 2017-02-24 19:36 UTC
Throw errors if the Rest API call return 4xx or 5xx  in [azureProvider](https://github.com/serverless/serverless-azure-functions/blob/master/provider/azureProvider.js)

**Comment by lostintangent** [comment] 2017-08-13 17:06
Closing this as a dupe of #71

**Closed by lostintangent** 2017-08-13 17:06 UTC
Labels: improvement
